### PR TITLE
[RFC] copy recursively

### PR DESCRIPTION
**Pull request by schnittstabil**
At least copying recursively makes it necessary to use a two step approach:
1. gather all files and folders to process
2. do the actual copy

Substantial advantages:
- [x] determine errors due to mutually recursively linked directories in advance (see test below)
- [ ] remove duplicated tasks (same source and destination)
- [ ] determine copy tasks with same destination to throw errors in advance
- [ ] calculate the total size during the first step, and emitting the progress during the second step
## 

The current approach of the first step:
1. use `globby` to gather all files and directories
2. for each directory path: [re-glob with `path + '/**/*'`](https://github.com/schnittstabil/cpy/blob/5c9e99bd8c9d2f7e42d1448a06cbe11714083ee7/cpy-tasks.js#L40-L50)

@all Comments on all aspects are highly welcome.

### CODE REVIEW

**Comment by jamestalmage** [comment]
When globbing the contents of a directory with `/somedir/**/*`, you want to avoid adding additional glob tasks for `/somedir/subdir/**/*`. See how I solved that [here](https://github.com/avajs/avafiles/blob/master/index.js#L212-L271).

Also, since you are going to be calling `glob`/`globby` many times, you want store and pass in [these caching options](https://github.com/avajs/ava-files/blob/master/index.js#L51-L54).

**Comment by YurySolovyov** [comment]
> calculate the total size during the first step, and emitting the progress during the second step

`cp-file` now has that.

> determine copy tasks with same destination to throw errors in advance

Can be racy.

**Comment by sindresorhus** [comment]
> When globbing the contents of a directory with /somedir/**/*, you want to avoid adding additional glob tasks for /somedir/subdir/**/*. See how I solved that here.

@jamestalmage Is that something that could maybe be added to `globby`? Sounds generally useful.

**Comment by sindresorhus** [comment]
> for each directory path: re-glob with path + '/**/*'

**Comment by sindresorhus** [comment]
I really like the idea of a two step process. My only concern is that it might cause some race issues. What   if something in the filesystem hierarchy changes between step 1 and 2? For example, we glob `foo/bar.jpg`, but by the time we start copying in step 2 that file no longer exist or has moved. How should that be handled? It might be a non-issue as the globbing itself is already racy (node-glob states that in its [docs](https://github.com/isaacs/node-glob#race-conditions)). Just thought I'd bring it up.

**Comment by sindresorhus** [comment]
> for each directory path: re-glob with path + '/**/*'

Would be better to do this in `globby`: https://github.com/sindresorhus/globby/issues/33

**Comment by sindresorhus** [comment]
@schnittstabil What are your thoughts on this now?

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/cpy/issues/61

**Pull request closed without merging**
