### PR TITLE
Don't create paths when copying files

### LINKED ISSUE #2: Source paths always preserved
Is this expected behavior for the CLI?

(at root of module)
```
flet@lappy:~/code/someproject$ ls assets/markup/
mock.html

flet@lappy:~/code/someproject$ cpy assets/markup/*.html dist

flet@lappy:~/code/someproject$ tree dist
dist
└── assets
    └── markup
        └── mock.html

```

I guess I was expecting it to work similarly to `cp` in linux?

```
flet@lappy:~/code/someproject$ cp assets/markup/*.html dist

flet@lappy:~/code/someproject$ tree dist
dist
└── mock.html
```

I realize this might not be the goal of this module and I'm prepared for this issue to be closed immediately :)

### PR DESCRIPTION
**Pull request by kevva**
This is the same behavior as `cp` which probably is what most people expects.

Fixes #2.

### CODE REVIEW

**Comment by schnittstabil** [comment]
Mhm, your test seems not to fail on HEAD~1.

**Comment by schnittstabil** [comment]
In addition, I think [cp-file](https://github.com/sindresorhus/cp-file) should provide the parent option…

**Comment by kevva** [comment]
It's not `cp-file` that decides what path structure to use. It only copies a file from one destination to another. The `--parents` option belong in here.

**Comment by schnittstabil** [comment]
Sorry, maybe my comment was somewhat misleading. Of course the `--parents` **cli** option belongs to `cpy`. But I think `cp-file` should handle it, i.e. `cp-file` should provide a `parents` **api** option.

**Comment by kevva** [comment]
Yes, I understood what you meant, but I don't agree. `cp-file` should only copy a file from one place to another. It's purpose is to be very low-level.

**Comment by schnittstabil** [comment]
I think it isn't such low-level, and tasks weren't divided such clearly between `cpy` and `cp-file`:
> # cp-file
> > Copy a file
> …

> # cpy
> > Copy files
> …

**Comment by schnittstabil** [comment]
> It only copies a file from one destination to another.

I don't think so:
> * User-friendly by creating non-existant destination directories for you.
> * Can be safe by turning off overwriting.

**Comment by sindresorhus** [comment]
> But I think cp-file should handle it, i.e. cp-file should provide a parents api option.

Why do you think so? Can you present a use-case?

**Comment by schnittstabil** [comment]
Maybe `parents` is an edge case, but APIs always suffer from working directory issues and I believe `cp-file` would also benefit from it.

From the project descriptions `cpy` and `cp-file` only differ in the number of files they copy.

Therefore, if I want to copy a single file, a `parent` option would keep my srcs DRY:
```js 
// w/o parents:
cpFile.sync('assets/style/app.css', 'web/assets/style/app.css');
cpFile.sync('assets/style/vendor.css', 'web/assets/style/vendor.css');

// w/ parents:
cpFile.sync('assets/style/app.css', 'web', {parents: true});
cpFile.sync('assets/style/vendor.css', 'web', {parents: true});
```

**Pull request closed without merging**
