### PR TITLE
Allow non-array argument by wrapping into new array

### PR DESCRIPTION
**Pull request by dmitriz**
Allow `cpy('src-file', 'dist')` instead of throwing error.

Simply wrap `src-file` into array and move on. ;)

### CODE REVIEW

**Comment by kevva** [comment]
Could you instead throw a `TypeError` if source isn't an `array`?

**Comment by dmitriz** [comment]
But why?

**Comment by sindresorhus** [comment]
Because that's what we asked for in the issue. Reason: Code clarity and type explicitness.

When reading some code it's not clear this can take multiple source files: `cpy('src-file', 'dist')`, which means you would never know since you don't read documentation.

**Comment by dmitriz** [comment]
I've just thought it would make it more user-friendly.
It is always pleasure to use software so intuitive that you don't need to read the documentation. ;)
Of course, I respect your opinion as library creator.

**Comment by sindresorhus** [comment]
Code is written once, but read and refactored many times. I always optimize for the latter.

**Comment by dmitriz** [comment]
Would then printing the actual value of `src` help future refactoring, something like:
```js
return Promise.reject(new TypeError(JSON.stringify(src) + ' is expected to be an array'));
```
Fail fast and noisy as they say ;)

**Comment by sindresorhus** [comment]
Too much handholding.

**Comment by dmitriz** [comment]
?
```js
return Promise.reject(new TypeError('First argument is expected to be an array'));
```

**Comment by kevva** [comment]
``Expected an array`` or ``Expected an array in `src` ``.

**Comment by dmitriz** [comment]
Just noticed the update already there, thanks! ;)

**Pull request closed without merging**
