### PR TITLE
enhance CLI to set cwd and whether or not to keep path structure

### PR DESCRIPTION
**Pull request by shaketbaby**
This PR adds 2 things to CLI
* specify the current CWD, default to process.cwd()
* specify whether to keep path structure

Both are already supported by the Node API.

### CODE REVIEW

**Comment by schnittstabil** [comment]
Thanks for this PR. Is it possible to make test cases for the new options? The last test in `test.js` seems to be a good starting point.

**Comment by shaketbaby** [comment]
Tests are added.

**Comment by schnittstabil** [comment]
LGTM. `--parents` is clearly lacking.
@sindresorhus, @kevva: What do you think about `--cwd <dir>`?

**Comment by sindresorhus** [comment]
Nice work @shaketbaby :)

**Pull request merged**
